### ISSUE TITLE
[GET /] Mudar o formato do query "f"

### ISSUE THREAD

**Issue by mrmorais** [ccsa-ufrn/sigeva-api-user#2]
Sugiro que no lugar de receber o query com o formato
```
GET ?p=1&c=2&f={"login":true,"createdAt":true} HTTP/1.1
```
Utilizar o formato
```
GET ?p=1&c=2&f=login,createdAt HTTP/1.1
```
Que fica mais fácil para fazer o tratamento (ex: não aceitar a solicitação do campo senha), e para passar para o query do Mongoose

**Comment by v1d3rm3** [comment]
Como explicado, fica ao seu critério.
Só peço que caso você queira mudar, modifique também a documentação da página inicial, por favor.
